# -*- coding: utf-8 -*-
"""Logistic Regression Deployment in Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJ0Bil7vf8nUoar_uZX4IrldXHtzp2np
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt


# Page Configuration
st.set_page_config(
    page_title="Life Insurance Prediction",
    page_icon="🛡️",
    layout="centered"
)

# Title
st.title("🛡️ Life Insurance Prediction")
st.write("Predict Insurance Purchase using Logistic Regression")

# Load Dataset
df = pd.read_csv("insurance_data.csv")

st.subheader("📊 Dataset")
st.dataframe(df)

#Visualisation

st.subheader("📈 Age vs Bought Insurance")

colors = ["red" if x == 0 else "green" for x in df["bought_insurance"]]

fig, ax = plt.subplots(figsize=(8,5))

ax.scatter(
    df["age"],
    df["bought_insurance"],
    c=colors,
    s=80
)

ax.set_xlabel("Age")
ax.set_ylabel("Bought Insurance")
ax.set_title("Age vs Bought Insurance")
ax.set_yticks([0, 1])
ax.set_yticklabels(["No", "Yes"])
ax.grid(True)

st.pyplot(fig)

# Train Model
X = df[['age']]
y = df['bought_insurance']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()
model.fit(X_train, y_train)

# User Input
st.subheader("📝 Enter Details")

age = st.number_input(
    "Enter your Age",
    min_value=1,
    max_value=100,
    value=25,
    step=1
)

# Prediction
if st.button("Predict"):

    user_data = pd.DataFrame({'age': [age]})

    prediction = model.predict(user_data)

    if prediction[0] == 1:
        st.success("✅ The person is likely to buy life insurance.")
    else:
        st.error("❌ The person is unlikely to buy life insurance.")

# Model Information
st.subheader("🤖 Model Details")

st.write("**Model Used:** Logistic Regression")
st.write("**Coefficient:**", model.coef_[0][0])
st.write("**Intercept:**", model.intercept_[0])